version: "3.9"  # optional but good to include

services:
  mysql-container:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
    ports:
      - "3307:3306"    # host 3307 mapped to container 3306
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p$${MYSQL_ROOT_PASSWORD} || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - mysql-data:/var/lib/mysql

  python-app:
    build: .
    depends_on:
      mysql-container:
        condition: service_healthy
    environment:
      MYSQL_HOST: mysql-container
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
      MYSQL_DATABASE: testdb

volumes:
  mysql-data:
