apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: python-mysql-app
        imagePullPolicy: Never  # ✅ Ensure it uses your local image
        env:
        - name: MYSQL_HOST
          value: mysql
        - name: MYSQL_USER
          value: testuser
        - name: MYSQL_PASSWORD
          value: testpassword
        - name: MYSQL_DATABASE
          value: testdb
